### PR TITLE
Vet clinic database: add "join table" for visits

### PR DESCRIPTION
**Pull request by CesarHerr**
-Create a table named vets with the following columns:

- [x] id: integer (set it as autoincremented PRIMARY KEY)
- [x] name: string
- [x] age: integer
- [x] date_of_graduation: date
- [x] There is a many-to-many relationship between the tables species and vets: a vet can specialize in multiple species, and a species can have multiple vets specialized in it. Create a "join table" called specializations to handle this relationship.
- [x] There is a many-to-many relationship between the tables animals and vets: an animal can visit multiple vets and one vet can be visited by multiple animals. Create a "join table" called visits to handle this relationship, it should also keep track of the date of the visit.

- Insert the following data for vets:

- [x] Vet William Tatcher is 45 years old and graduated Apr 23rd, 2000.
- [x] Vet Maisy Smith is 26 years old and graduated Jan 17th, 2019.
- [x] Vet Stephanie Mendez is 64 years old and graduated May 4th, 1981.
- [x] Vet Jack Harkness is 38 years old and graduated Jun 8th, 2008.

- Insert the following data for specializations:

- [x] Vet William Tatcher is specialized in Pokemon.
- [x] Vet Stephanie Mendez is specialized in Digimon and Pokemon.
- [x] Vet Jack Harkness is specialized in Digimon.

- Insert the following data for visits:

- [x] Agumon visited William Tatcher on May 24th, 2020.
- [x] Agumon visited Stephanie Mendez on Jul 22th, 2020.
- [x] Gabumon visited Jack Harkness on Feb 2nd, 2021.
- [x] Pikachu visited Maisy Smith on Jan 5th, 2020.
- [x] Pikachu visited Maisy Smith on Mar 8th, 2020.
- [x] Pikachu visited Maisy Smith on May 14th, 2020.
- [x] Devimon visited Stephanie Mendez on May 4th, 2021.
- [x] Charmander visited Jack Harkness on Feb 24th, 2021.
- [x] Plantmon visited Maisy Smith on Dec 21st, 2019.
- [x] Plantmon visited William Tatcher on Aug 10th, 2020.
- [x] Plantmon visited Maisy Smith on Apr 7th, 2021.
- [x] Squirtle visited Stephanie Mendez on Sep 29th, 2019.
- [x] Angemon visited Jack Harkness on Oct 3rd, 2020.
- [x] Angemon visited Jack Harkness on Nov 4th, 2020.
- [x] Boarmon visited Maisy Smith on Jan 24th, 2019.
- [x] Boarmon visited Maisy Smith on May 15th, 2019.
- [x] Boarmon visited Maisy Smith on Feb 27th, 2020.
- [x] Boarmon visited Maisy Smith on Aug 3rd, 2020.
- [x] Blossom visited Stephanie Mendez on May 24th, 2020.
- [x] Blossom visited William Tatcher on Jan 11th, 2021.

- Write queries to answer the following:

- [x] Who was the last animal seen by William Tatcher? :point_down: 
image
- [x] How many different animals did Stephanie Mendez see? :point_down: 
image
- [x] List all vets and their specialties, including vets with no specialties. :point_down: 
image
- [x] List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020. :point_down: 
image
- [x] What animal has the most visits to vets? :point_down: 
image
- [x] Who was Maisy Smith's first visit? :point_down: 
image
- [x] Details for most recent visit: animal information, vet information, and date of visit. :point_down: 
image
- [x] How many visits were with a vet that did not specialize in that animal's species? :point_down: 
image
- [x] What specialty should Maisy Smith consider getting? Look for the species she gets the most. :point_down: 
image

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented; Ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. 

**Kindly remove/update all aspects similar to the underlined:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rloterh** [comment]
Hi @CesarHerr 

Let's also include the Getting Started section of the ReadMe. I missed this aspect previously.

 Cheers!

**Review by rloterh — COMMENTED** [review]
Hi César, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented; Let's ensure that all main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, by including the Getting Started section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by ShadyShawkat — APPROVED** [review]
## Hi @CesarHerr, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by CesarHerr** [comment]
@ShadyShawkat  Thanks for your review!!

**Pull request merged**
